title: Built with Nix

remote_theme: mmistakes/minimal-mistakes

logo: badge.svg

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
